from catalogue import *
c1 = CountryCatalogue("data.txt", "continent.txt")
#print(c1.findCountry("Brazil"))
#print(c1.setPopulationOfCountry("Brazil", 21))
#print(c1.findCountry("Brazil"))
#print(c1.setAreaOfCountry("brazil", 58))
#print(c1.findCountry("Brazil"))
#print(c1._countryCat)
#print(c1._cDictionary)
#c1.addCountry("hadiland", 1, 21, "Africa")
#print(c1.findCountry("hadiland"))
#print(c1._countryCat)
#print(c1._cDictionary)
#print(c1.addCountry("Brazil", 4, 53, "Antarctica"))
#print(c1._countryCat)
print(c1._cDictionary)
#c1.deleteCountry("BrAzIl")
#print(c1._countryCat)
#print(c1._cDictionary)
#c1.printCountryCatalogue()
#print(c1._cDictionary)
#c1.addCountry("niGGa", 6, 56, "North AMeRicA")
c1.printCountryCatalogue()
#print(c1._cDictionary)
#print(c1.getCountriesByContinent("aSiA"))
#print(c1.getCountriesByArea("AsIA"))
#print(c1.getCountriesByPopulation("bOoTy"))
#print(c1.getCountriesByPopulation("EuROpE"))
#print(c1.getCountriesByPopulation(""))
#print(c1.getCountriesByPopulation("FaCUk"))
print(c1.findMostPopulousContinent())
print(c1.saveCountryCatalogue("txt.txt"))
